import React from "react";
import {
  Activity,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  Brain,
  Briefcase,
  CalendarDays,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheckBig,
  CirclePlus,
  Copy,
  CornerDownRight,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Download,
  EllipsisVertical,
  Eye,
  FileText,
  FlaskConical,
  FolderOpen,
  GitBranch,
  Handshake,
  Info,
  KeyRound,
  Landmark,
  Layers3,
  Lightbulb,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockOpen,
  LogOut,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Moon,
  Network,
  Play,
  Rocket,
  RotateCcw,
  Save,
  Scale,
  Search,
  SendHorizontal,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Terminal,
  Trash2,
  TriangleAlert,
  Users,
  WifiOff,
  Wrench,
  X,
  Zap,
} from "lucide-react";

const iconMap = {
  account_balance: Landmark,
  account_tree: GitBranch,
  add_circle: CirclePlus,
  admin_panel_settings: Shield,
  analytics: BarChart3,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  balance: Scale,
  bar_chart: BarChart3,
  bolt: Zap,
  calendar_month: CalendarDays,
  chat_bubble: MessageCircle,
  check_circle: CircleCheckBig,
  chevron_right: ChevronRight,
  close: X,
  compare_arrows: ArrowLeftRight,
  content_copy: Copy,
  dark_mode: Moon,
  dashboard: BarChart3,
  database: Database,
  delete: Trash2,
  diamond: Diamond,
  download: Download,
  encrypted: LockKeyhole,
  engineering: Wrench,
  expand_more: ChevronDown,
  folder_open: FolderOpen,
  folder_shared: FolderOpen,
  forum: MessageSquare,
  gavel: Scale,
  groups: Users,
  handshake: Handshake,
  history_edu: FileText,
  hub: Network,
  info: Info,
  layers: Layers3,
  light_mode: Sun,
  lightbulb: Lightbulb,
  lock: Lock,
  lock_open: LockOpen,
  logout: LogOut,
  magic_button: Sparkles,
  mail: Mail,
  map: Map,
  memory: Cpu,
  monitoring: Activity,
  more_vert: EllipsisVertical,
  notifications: Bell,
  payments: CreditCard,
  play_arrow: Play,
  psychology: Brain,
  psychology_alt: Brain,
  radio_button_unchecked: Circle,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  rule: Scale,
  save: Save,
  science: FlaskConical,
  search: Search,
  security: Shield,
  send: SendHorizontal,
  settings: Settings,
  settings_input_component: SlidersHorizontal,
  share: ArrowRight,
  smart_toy: Bot,
  subdirectory_arrow_right: CornerDownRight,
  sync: LoaderCircle,
  task_alt: BadgeCheck,
  terminal: Terminal,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  vpn_key: KeyRound,
  vpn_lock: ShieldCheck,
  warning: TriangleAlert,
  wifi_off: WifiOff,
  work: Briefcase,
};

export default function AppIcon({ name, className, strokeWidth = 2, ...props }) {
  const Icon = iconMap[name] || Shield;
  return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} {...props} />;
}
